name: Latest images
env:
  UPDATER_IMAGE: "ghcr.io/dependabot/dependabot-updater-"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - "common/lib/dependabot.rb"

jobs:
  date-version:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.DATE_BASED_VERSION }}
    steps:
      - id: date
        name: Set date based version
        # The v2 tag is the Updater image tag, not related to the core version.
        # This env var has to be set here so all versions are the same.
        run: |
          export DATE_BASED_VERSION=v2.0.$(date +%Y%m%d%H%M%S)
          echo "DATE_BASED_VERSION=$DATE_BASED_VERSION" >> $GITHUB_OUTPUT
  push-updater-image:
    name: Deploy
    runs-on: ubuntu-latest
    needs: date-version
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { name: gradle, ecosystem: gradle }
          - { name: maven, ecosystem: maven }
          - { name: npm_and_yarn, ecosystem: npm }
    env:
      COMMIT_SHA: ${{ github.sha }}
      NAME: ${{ matrix.suite.name }}
      ECOSYSTEM: ${{ matrix.suite.ecosystem }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the dependabot-updater-<ecosystem> image
        # despite the script input being $NAME, the resulting image is dependabot-updater-${ECOSYSTEM}
        run: script/build ${NAME}

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
         push: true
         tags: |
          473733881755.dkr.ecr.us-east-1.amazonaws.com/workflows/dependabot-updater:$COMMIT_SHA
          473733881755.dkr.ecr.us-east-1.amazonaws.com/workflows/dependabot-updater:${{ needs.date-version.outputs.date }}
          473733881755.dkr.ecr.us-east-1.amazonaws.com/workflows/dependabot-updater:latest
      
      - name: Set summary
        run: |
          echo "updater uploaded with tag \`$COMMIT_SHA\`" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${UPDATER_IMAGE}${ECOSYSTEM}:$COMMIT_SHA" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
